---
title: |
    TEI 2026
    <br>Creating Connections, Unsettling Practices
subtitle: |
    August 10-14, 2026
    <br>University of British Columbia, Vancouver, BC, Canada
title-block-banner: "logos/ubc.jpg"
---

<!-- 
## Keynotes 

```{=html}
 <div class="cards">
 

        <div class="speaker-card">
          <span class="speaker-tag">Opening Plenary · Aug 11</span>
          <p class="speaker-name">Jon Corbett</p>
          <p class="speaker-affiliation">
            Assistant Professor, School of Interactive Arts & Technology<br>
            Simon Fraser University
          </p>
          <p class="speaker-bio">
          </p>
        </div>

        <div class="speaker-card">
          <span class="speaker-tag">Film Screening and Discussion · Aug 13</span>
          <p class="speaker-name">Julia Flanders and Sarah Connell</p>
          <p class="speaker-affiliation">
            Women Writers Project
          </p>
         <p class="speaker-bio">
          </p>
        </div>

    <div class="speaker-card">
          <span class="speaker-tag">Closing Plenary · Aug 15</span>
          <p class="speaker-name">Susan Brown</p>
          <p class="speaker-affiliation">
            Professor of English and Canada Research Chair in Collaborative Digital Scholarship,<br>
            University of Guelph
          </p>
        <p class="speaker-bio">
          </p>
        </div>

</div>
``` -->

The University of British Columbia and Simon Fraser University will co-host TEI 2026. This is the first time the TEI conference will be held in Vancouver and the third time in 26 years that it will be held in Canada. The annual conference provides an opportunity for a diverse international group of researchers to advance text encoding practices, demonstrate new tools, pose questions across disciplines, learn from each other, and train the next generation of scholars in the principles and practices of text encoding. The 5-day conference will host academic panels, poster presentations, tool demonstrations, public keynotes, and plenaries, plus innovative outreach activities including a film screening, public exhibit, open workshops, capacity-building meetings, and collaborative working events. 

We look forward to welcoming you for the in-person conference, **August 10-14th**. Workshops, panels, and presentations will be held at UBC's Vancouver campus with the final keynote at Simon Fraser University's Harbour Center campus in downtown Vancouver. 

Now currently called "Vancouver", the lands on which the conference takes place include the territories of the xʷməθkʷəy̓əm (Musqueam), Sḵwx̱wú7mesh (Squamish), and səlilwətaɬ (Tsleil-Waututh) Nations.