---
title: Schedule
---

## Tentative Schedule

We are happy to provide the tentative schedule to aid in travel planning. Please note that some times and locations are subject to change until the final conference schedule is posted.

### Monday, August 10th

| Time | Activity | Location |
|------|----------|----------|
| 8:00 am – 4:30 pm | Registration | Koerner, 5th Floor, Common Area |
| 9:00 am – 12:00 pm | Public Workshop 1 | Koerner, 5th Floor, Presentation Room |
| 9:00 am – 12:00 pm | Registered Workshop | Koerner, 4th Floor, Digital Scholarship Lab |
| 12:00 – 1:30 pm | Lunch (no host) | |
| 1:30 – 4:30 pm | Public Workshop 2 | Koerner, 5th Floor, Presentation Room |
| 1:30 – 4:30 pm | Public Workshop 3 | Koerner, 4th Floor, Digital Scholarship Lab |
| 5:00 – 8:00 pm | Conference Opening and Reception | Green College |

### Tuesday, August 11th

| Time | Activity | Location |
|------|----------|----------|
| 8:00 – 8:30 am | Registration & Coffee | BuTo 323 |
| 8:30 – 10:15 am | Paper Sessions | B208 |
| 10:30 am – 12:15 pm | Paper Sessions | B208 / B210 |
| 12:15 – 1:45 pm | Working Groups + Lunch| |
| 1:45 – 3:15 pm | Poster Session + Lightning Talks | Koerner, 5th Floor, Common Area |
| 3:30 – 5:00 pm | Workshops | Koerner, 4th & 5th Floors |
| 6:00pm - | Dine Around |

### Wednesday, August 12th

| Time | Activity | Location |
|------|----------|----------|
| 8:00 – 8:30 am | Registration & Coffee | BuTo 323 |
| 8:30 – 10:15 am | Long Paper Sessions | D316 / D322 |
| 10:30 am – 12:15 pm | Long Paper Sessions / SIGs | D316 |
| 12:15 – 1:45 pm | Lunch (no host) | |
| 1:45 – 3:15 pm | Long Paper Session | A102 |
| 3:30 – 5:00 pm | Public Film Screening and Discussion | A102 |
| 6:00 – 8:00 pm | Evening Social | Koerner's Pub |

### Thursday, August 13th

| Time | Activity | Location |
|------|----------|----------|
| 8:00 – 8:30 am | Registration & Coffee | BuTo 323 |
| 8:30 – 10:15 am | Short Paper Sessions | B208 / B210 |
| 10:30 am – 12:15 pm | Public Panel / Short Paper Sessions | IKBLC / B210 |
| 12:15 – 1:45 pm | Working Groups + Lunch| |
| 1:30 – 2:00 pm | Coffee Break | BuTo 323 |
| 2:30 – 4:00 pm | Decolonization Tour / SIGs | |
| 7:00 – 9:00 pm | Banquet | Wildlight Kitchen + Bar |

### Friday, August 14th

| Time | Activity | Location |
|------|----------|----------|
| 10:00 – 11:00 am | Coach to SFU Harbour Centre | Departs Walter Gage Residence |
| 11:00 am – 1:00 pm | AGM and Catered Business Lunch | Segal Centre, Harbour Centre (SFU Downtown) |
| 1:00 – 2:30 pm | Closing Plenary | Segal Centre, Harbour Centre (SFU Downtown) |
